### PR TITLE
Fix merge conflicts with upstream

### PR DESCRIPTION
**Pull request by mmirate**
Hi there! I saw that https://github.com/prusa3d/Prusa-Firmware/pull/2657 has been sitting conflicted for several weeks and I'm a big fan of the ArcWelder work *minus upstream's firmware problems*. (my machine already requires Bondtech's fork of the firmware. oy.)

Thus, with the help of git-imerge, I merged the upstream MK3 branch into your PR-branch, producing this PR-branch here. I suspect I even got the new EEPROM size correct and consistently ordered your new EEPROM elements with upstream's new "travel acceleration" EEPROM element.

Unfortunately, I don't presently have the infrastructure to attempt compiling or testing this. (If I did, I wouldn't be so daunted by the prospect of rebasing your stuff against the Bondtech fork myself, and flashing the result.)

While GitHub does allow you to preview how your branch would change as a result of merging this PR, I suspect that's going to be a lot of noise. Instead, you probably want to see how your *PR changes* would, themselves, change as a result of merging this PR. This can be done by viewing the comparison of my branch and upstream, minus those nasty whitespace changes: https://github.com/prusa3d/Prusa-Firmware/compare/MK3...mmirate:MergedMK3?w=1

Thank you for your consideration.

### CODE REVIEW

**Comment by FormerLurker** [comment]
Very cool!  I will review this ASAP!  I'm finishing up a new printer ATM, which should allow me to test against several boards/firmware quickly, and should help reduce printing time to make each test faster.  Because of that my MK2 has been pretty much printing constantly for the last month or so, leaving little time to get to my fork here, but you seem to have solved that for me!  

I don't think I'll have to may problems checking out your changes, and thanks for the nice compare link!  I'll let you know what I find.

**Comment by mmirate** [comment]
~~This doesn't appear to have merge conflicts after RC2 came out, which is why I suspect it will merge incorrectly, as RC2's description claims it contains EEPROM changes.~~

~~EDIT 2021-04-17: I plan to take another look at this later today.~~ Done, see next comment.

**Comment by mmirate** [comment]
Okay, now I see what's going on. The RC code is in a separate branch that isn't yet merged back to the MK3 branch.

I assume that Prusa won't be wanting to merge your PR in the middle of their release process. I also assume that Prusa will be merging the MK3_3.10.0 branch back into MK3 once 3.10.0 is out.

On those assumptions, I've gone ahead and merged MK3_3.10.0 into this PR-branch, and I intend to do so again after each RC and the final 3.10.0 release, so that each individual such merge will be as easy as possible.

If you feel these assumptions are wrong, just tell me to force-push a reset of this PR-branch back to https://github.com/FormerLurker/Prusa-Firmware/pull/1/commits/01a1f063b830b6abb556eae807805fd443083972 where it was before, and I will happily do so.

**Comment by FormerLurker** [comment]
Merged, and thank you!  I REALLY hope this, or something similar, gets merged into the master asap.

**Comment by FormerLurker** [comment]
Looks like all checks have passed!

**Pull request merged**
