### PR TITLE
Fix the merge conflict with 5c8a231

### PR DESCRIPTION
**Pull request by mmirate**
https://github.com/FormerLurker/Prusa-Firmware/commit/5c8a231ed6a14f6b12f930926002527a3f518e06 created a new merge-conflict due to a bit of stray whitespace that my editor nuked during previous merges. This should fix that.

### CODE REVIEW

**Comment by mmirate** [comment]
I've updated this PR to account for further merge conflicts that have happened since it was opened.

**Comment by FormerLurker** [comment]
I am so sorry I missed this!  V sorry.  Will merge as soon as I am in front of my pc.

**Comment by FormerLurker** [comment]
This has been merged.  FYI, I searched my email and I can't find any notifications from this PR!  I'm very glad you commented on the issue in the Prusa repo, else who knows when I'd have seen this..

I really appreciate you keeping this fork up-to-date.  It's SUPER appreciated.

**Comment by mmirate** [comment]
You're welcome. As for the notifications, navigate to anywhere in your fork (e.g. this PR) and check the top right corner:

image

The "All Activity" setting is generally helpful for any repositories you own; other settings will likely produce the symptom you've observed.

**Comment by mmirate** [comment]
So, squash-merges collapse all of the original Prusa commits in with my changes into a single commit, which itself cannot be merged correctly back into the upstream repo. Your feature-branch must contain all those original commits, as-is.

To fix this ... you'll need to undo this merge, then redo it via merge-commit or via rebase; and that all has to happen locally on your side followed by a force-push to your MK3 branch.

**Comment by FormerLurker** [comment]
So, first, I was pretty surprised I wasn't already subscribed to all activity!  Perhaps it's because I forked this repo.  Thanks for the tip, I have corrected that issue.

Next, regarding the squash, I am so used to doing that for PRs into my own repo, I just did it by reflex.  I will try to fix that now.

**Comment by FormerLurker** [comment]
I've been researching how to do this (this is probably the most complicated thing I've ever attempted on github), and I wanted to run this by you since you seem to me much more knowledgeable than I am.  I'm guessing a standard revert isn't going to cut it for this.

So, I cloned the current remote MK3 branch locally, then I believe I need to do a hard reset:

```
git reset --hard  621e150 
```
I am pretty sure that SHA is the correct one.  I double checked that here:

image


Next, if I force push this:

```
git push origin MK3 -force
```

That should erase the history of the merge commit, right?  If so, I'm still missing how I could re-merge this PR.

Ugh.. all this because of one small mistake, lol!  I really need to dedicate a weekend to learning more about git.

**Comment by mmirate** [comment]
Other than what I presume is a formatting error here (there's two dashes in `--force`), you're on the right track so far.

As for redoing the merge, there's two ways to do this.

In either case, start from just after that force-push of your MK3 branch, and then add my fork as a remote. (Something like `git remote add mmirate https://github.com/mmirate/Prusa-Firmware`, then `git fetch --all` to make that remote's branches available to you locally.)

1. To create a merge commit (a la "Merge pull request"), `git merge mmirate/MergedMK3YetAgain` and push that.

2. To merge via rebase (a la "Rebase and merge"), uhh, actually, on second thought, that's kinda complicated. Just go with option 1.

**Comment by FormerLurker** [comment]
Wow, thanks for your help with that!  These kinds of destructive operations always make me super nervous, so your advice here was very much appreciated.   Also, I added you as a collaborator to this repo in case you have any interest in that.

**Pull request merged**
